#!/usr/bin/python3

from models.engine.file_storage import FileStorage
from models.base_model import BaseModel

fs = FileStorage()

new_obg = {"id": "11294ed2-db69-4766-9a93-2068a193d21b",
                "created_at": "2024-02-20T00:43:56.120135",
                "updated_at": "2024-02-20T00:43:56.120152",
                "__class__": "State"}

new_base = BaseModel(new_obg)
print(new_base)
# fs.new(new_base)
# fs.save()